# Site settings
title: Gustavo Bakker
email: gustavobakker@hotmail.com
url: https://github.com/gusbakker
description: "Gustavo Bakker - Software Developer and independent AI/ML researcher"
keywords: "artificial intelligence, machine learning, software developer, researcher"
skills: "Software Developer - Independent AI/ML Researcher"
meta_author: Bakker Gustavo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1d2938 #1d2938
  primary-rgb: "240, 254, 255" #"128,179,255"
  secondary: 101e33 #101e33
  secondary-dark: 19354c #19354c
  secondary-soft: 128f76 #128f76

# background image
background-image: holland.JPG

# Footer settings
footer:
  copyright: Gustavo Bakker
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    twitter: https://twitter.com/gusbakker
    github: http://github.com/gusbakker
    linkedin: https://www.linkedin.com/in/gustavo-bakker-9631628b
    medium: https://medium.com/@gustavobakker
    youtube: https://www.youtube.com/user/gusbakker


# Postal address (add as many lines as necessary)
address:
  - line: Lisbon
  - line: Portugal

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
